### ISSUE TITLE
TCC

### ISSUE THREAD

**Issue by Kovalski-rgb** [Knightleo602/Guitarino#1]
pq a gnt nn fez isso, só que com conexão com internet pro tcc

**Comment by Kovalski-rgb** [comment]
pq a gnt é burro

**Comment by Knightleo602** [comment]
eu concordo

**Comment by Knightleo602** [comment]
eu concordo de novo

**Comment by Kovalski-rgb** [comment]
devo confirmar sua concordância

**Comment by Knightleo602** [comment]
vou confirmar a sua confirmação sobre eu concordando mais uma vez depois de eu ja ter concordado que a gente e burro e não continuo o guitarino pro tcc

**Comment by Kovalski-rgb** [comment]
ufa, ainda bem

**Comment by Knightleo602** [comment]
sim
